/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 girl_frontend.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/girl_frontend.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.124, 0]} scale={0.339}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.border_red} />
      </group>
      <group position={[0.175, 1.27, 0]} scale={0.164}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.pants} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.pants_border} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials.skin} />
      </group>
      <group position={[0.301, 2.647, 0]} rotation={[0, 0, 0.61]} scale={0.164}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.border_red} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials.skin} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials.skin} position={[0.005, 3.261, -0.01]} scale={-0.272} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.skin} position={[-0.005, 2.993, 0.006]} scale={0.081} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.skin} position={[0.355, 3.221, 0.317]} scale={-0.06} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.hair} position={[0.005, 3.261, -0.01]} scale={-0.272} />
    </group>
  )
}

useGLTF.preload('/girl_frontend.glb')
